### ISSUE TITLE
Miscalculated sum of BE

### ISSUE THREAD

**Issue by Idrinth** [Faltenreich/Diaguard#1]
There seems to be a calculation issue when adding 100g of "Joghurt, Vanille" and 200g of "Vollmilch, UHT", instead of adding up to 2BE they add up to 1.1

**Comment by Faltenreich** [comment]
There has been a rounding error in the [FoodInputView](https://github.com/Faltenreich/Diaguard/blob/b7a2c987ac83e6c26d748035beb79054d30aaa93/diaguard/src/main/java/com/faltenreich/diaguard/feature/food/input/FoodInputView.java#L175) which can be found when adding food to the meal value of an entry. This seems only to be a user interface-related problem as the value itself is stored correctly in carbohydrates.

This bug has been fixed in https://github.com/Faltenreich/Diaguard/commit/3e46da39155f1bd485a6796a5798c45f431f8b43 which replaces the split-up Ticker views with a simplified TextView. The bugfix will be released alongside feature/therapy in version 4.0.0.

Thank you for your help!
