### ISSUE TITLE
Feature: multi device / sync / online

### ISSUE THREAD

**Issue by NotSoImportant** [Faltenreich/Diaguard#17]
have a possibility to access the user data from multiple devices (without need to always do manual backups).

If there would be a sync functionality, any storage could be used to achive this.

**Comment by Faltenreich** [comment]
This feature makes perfectly sense but has not been implemented yet because of privacy policy concerns. Currently all data is being stored on the user's end device. Synchronizing data would require automatic transmission of the user's data to remote and/or third party services. 

This would affect the privacy policy in a way that I am not able to supervise as independent developer. Therefore I will cancel this feature until something changes which allows a simpler and more maintainable solution.

**Comment by NotSoImportant** [comment]
fine. thank you
