### ISSUE TITLE
Highlight manually added/edited food database entries

### ISSUE THREAD

**Issue by drunken-dwarf** [Faltenreich/Diaguard#18]
Currently I can not distinguish between entries from an online database (which might be wrong/not suiting my needs) and my own additions.
Since I do not want to add an indicator to the title myself (because I consider it a dirty workaround), I'd like to have something like a star or a plus sign behind the title or a bold font.

I think it would make adding food entries easier to manage.

**Comment by Faltenreich** [comment]
Good idea, since e.g. "Common food" is already being highlighted (in the detail view). 

Custom food could be highlighted the same way with little effort. Highlighting it inside the food list would take more effort but I will check if there is a good and intuitive way to implement this. Of course you are free to do so first by creating a pull request.

Thank you for your feedback!
