### ISSUE TITLE
Make "activity" less ambiguous

### ISSUE THREAD

**Issue by drunken-dwarf** [Faltenreich/Diaguard#20]
I'd like to add "activity" like I can add food: As their own entries.
Currently I can only add "15 minutes of activity".

I'd like to be able to add "50 push-ups", "20 sit-ups", "30 minutes of chopping wood", etc.

**Comment by Faltenreich** [comment]
In my opinion this could exhaust the main use case of this app: threating Diabetes. Diaguard handles activities since they influence Blood Sugar and other Diabetes-related data, but it is no fitness app. Therefore enhancing the activity has been postponed multiple times in favor of more Diabetes-specific topics.

My current plan to enhance activites without breaking the boundaries of this app, is support custom categories: #27
