### ISSUE TITLE
strange CSV export or how to import in into KNIME or LibreOffice

### ISSUE THREAD

**Issue by keynator** [Faltenreich/Diaguard#39]
Hi,
thank for the nice tool. I wanted to to an analysis of my date in an external tool like KNIME and used the CSV export tool. But the format of the exported data is strange for me and I do not know how to import it into KNIME properly.

What I get is:

"11.11.2022 11:11";
"bloodsugar";"110"
"insulin";"28";;
"meal";"6"
"11.11.2022 12:12";
"bloodsugar";"110"
"insulin";"9";;
"meal";"3"

So the first column is data *or* "bloodsugar", "insulin" and so on. Can you give me some tips how to import it without some programming.

It would help me if all the data for on date/time would be in one line. Even better would each "category" like "boodsugar" would have it own column like:

"Date","bloodsugar", "meal", "insulin-bolus", "insulin-correction", "insulin-basal"
"11.11.2022 11:11";"110","6","28",,
"11.11.2022 12:12";"110","3","9",,

**Comment by Faltenreich** [comment]
I agree that the current formatting of CSV exports is not optimal and I will try to optimize it with the upcoming major release. Until then you can read the exported CSV as follows:

- Every row with a date and time marks the start of a new entry
- Subsequent rows contain measurements of that entry, with the first column declaring the category and the second column providing the input value

This structure supports the fact that one entry might contain multiple measurements, but your suggestion is far more readible and I will look into a way to improve the structure like you did without losing the 1:n connection between entry and measurements.

Since you are trying to import data, I strongly suggest using the backup instead of the export. The backup format is optimized to be machine-read while the export format is optimized for the human eye, e.g. when opening the CSV in Excel.

**Comment by keynator** [comment]
Sorry for the late reply...
The backup CSV file has a similar structure and I see no possibility to import it directly. It is store the same way in the internal sqlite database?
It looks similar to JSON. Maybe I write a parser that converts it into JSON.
